"""Generate docs/phase_9 from the stored records.

Every measured number in the four documents comes from a record under
`artifacts/med-deploy-v1/` (or, for the comparison with the Phase 6 latency, the
untouched Phase 6 record). Procedures and explanations are written here; results
are not. A test regenerates the documents and requires an exact match, so a
document cannot drift from its records.
"""

from __future__ import annotations

import json
from pathlib import Path

from med_deploy import version as V
from med_deploy.coverage_map import COVERAGE

STATIC_LINKS = {
    "api": "../phase_6/API_CONTRACT.md",
    "errors": "../phase_6/ERROR_BEHAVIOR.md",
    "flow": "../phase_6/SCORING_FLOW.md",
    "ui": "../phase_7/UI_GUIDE.md",
    "runbook": "../phase_8/RUNBOOK.md",
    "monitoring": "../phase_8/MONITORING.md",
    "policy": "../phase_5/THRESHOLD_POLICY.md",
    "card": "../phase_5/MODEL_CARD.md",
    "ac": "../phase_1/ACCEPTANCE_CRITERIA.md",
    "scenarios": "../phase_1/SCENARIOS.md",
    "leakage": "../phase_2/DATA_QUALITY_AND_LEAKAGE.md",
}


# ------------------------------------------------------------------ records


def load_records(root: Path) -> dict:
    root = Path(root)

    def read(path: Path):
        full = root / path
        return json.loads(full.read_text(encoding="utf-8")) if full.exists() else None

    return {
        "scenarios": read(V.SCENARIO_RECORD),
        "bundle": {name: read(path) for name, path in V.BUNDLE_RECORDS.items()},
        "reads": read(V.READS_RECORD),
        "images": read(V.IMAGES_RECORD),
        "runs": (read(V.RUNS_RECORD) or {}).get("runs", {}),
        "rebuild": read(V.REBUILD_RECORD),
        "digests": read(V.DIGESTS_RECORD),
        "mutations": read(V.MUTATION_RECORD),
        "clean": read(V.CLEAN_CHECKOUT_RECORD),
        "smoke": {name: read(path) for name, path in V.SMOKE_RECORDS.items()},
        "latency": read(V.LATENCY_RECORD),
        "phase6_latency": read(Path(V.LATENCY_PATH)),
        "rehearsal": {name: read(path) for name, path in V.REHEARSAL_RECORDS.items()},
        "browser": read(V.BROWSER_RECORD),
        "platform": read(V.PLATFORM_RECORD),
    }


# ------------------------------------------------------------------ formatting


def _table(headers: list[str], rows: list[list]) -> str:
    def cell(value) -> str:
        return str(value).replace("|", "\\|").replace("\n", " ")

    lines = ["| " + " | ".join(headers) + " |", "| " + " | ".join("---" for _ in headers) + " |"]
    lines += ["| " + " | ".join(cell(item) for item in row) + " |" for row in rows]
    return "\n".join(lines)


def _when(stamp: str | None) -> str:
    return stamp.replace("T", " ").replace("Z", " UTC") if stamp else "not run"


def _ms(value: float) -> str:
    return f"{value:.2f} ms"


def _minutes(seconds: float) -> str:
    whole = int(round(seconds))
    return f"{seconds:.1f} s ({whole // 60}m{whole % 60:02d}s)" if whole >= 60 else f"{seconds:.1f} s"


def _score(value: float) -> str:
    return f"{value:.7f}" if value >= 1e-3 else f"{value:.3e}"


def _mib(size: int | None) -> str:
    return "not reported" if size is None else f"{size / 2**20:.0f} MiB"


def _counts(run: dict) -> str:
    parts = [f"{run[key]} {label}" for key, label in (("passed", "passed"), ("failed", "failed"), ("errors", "errors"), ("skipped", "skipped"), ("deselected", "deselected"), ("checks_passed", "checks passed")) if key in run]
    return ", ".join(parts) or run.get("summary_line") or "no summary line"


def _storage(info: dict | None) -> str:
    if not info:
        return "pandas not installed"
    return f"option `{info['option']}`, dtype `{info['series_dtype']}`, held in `{info.get('backend', 'unknown')}`"


def _kv(counts: dict) -> str:
    """{'assessed': 1000} as `assessed 1000`."""
    return ", ".join(f"{key} {value}" for key, value in counts.items()) or "none"


def _ports(ports: dict) -> str:
    return ", ".join(f"{inside} to {' and '.join(outside)}" for inside, outside in ports.items()) or "none"


def _status(ok: bool | None) -> str:
    return {True: "passed", False: "FAILED", None: "not run"}[ok]


def _missing(name: str) -> str:
    return f"_Not run: the record `{name}` does not exist._\n"


# ---------------------------------------------------------------- TEST_REPORT


def test_report(rec: dict) -> str:
    out: list[str] = []
    out.append("# Phase 9 — Test report\n")
    out.append(
        "This report is generated by `python -m med_deploy report` from the records in `artifacts/med-deploy-v1/`. "
        "Every number below comes from a command that was run and stored; nothing here is typed by hand. "
        "All data is fictional and on reserved `.example` domains. No check re-evaluated the frozen policy, and none read a frozen test row: "
        "the frozen test subsets were scored once in Phase 5, and [the threshold policy](" + STATIC_LINKS["policy"] + ") holds that result.\n"
    )
    served = (rec["scenarios"] or {}).get("bundle", {})
    if served:
        out.append(
            f"Served bundle: contract `{served['contract_version']}`, snapshot `{served['snapshot_id']}`, features `{served['feature_spec_version']}`, "
            f"model `{served['model_version']}`, policy `{served['policy_version']}`, `T_warn = {served['T_warn']!r}`, blocking disabled. Scores are risk scores, not probabilities.\n"
        )

    out.append("## What was run\n")
    runs = rec["runs"]
    rows = []
    for name, label in (
        ("full_pytest", "Full test suite (release gate)"),
        ("fast_pytest", "Fast selection (CI)"),
        ("phase9_suite", "Phase 9 tests"),
        ("validate", "Dataset validation (release gate)"),
    ):
        run = runs.get(name)
        rows.append([label, f"`{run['command']}`" if run else "not run", _when(run["date_utc"]) if run else "not run", _minutes(run["seconds"]) if run else "-", _counts(run) if run else "-", _status(run["exit_code"] == 0) if run else "not run"])
    clean = rec["clean"]
    rows.append(["CI steps in a clean copy and a fresh virtual environment", "`python -m med_deploy clean-checkout`", _when(clean["date_utc"]) if clean else "not run", _minutes(sum(s["seconds"] for s in clean["steps"])) if clean else "-", f"{len(clean['steps'])} steps" if clean else "-", _status(clean["passed"]) if clean else "not run"])
    for mode in ("process", "container"):
        record = rec["smoke"][mode]
        rows.append([f"End-to-end smoke, API as a {mode}", "`python -m med_deploy smoke`", _when(record["date_utc"]) if record else "not run", "-", f"{sum(1 for c in record['checks'] if c['passed'])} of {len(record['checks'])} checks" if record else "-", _status(record["passed"]) if record else "not run"])
    latency = rec["latency"]
    rows.append(["Warm latency, API container", "`python -m med_deploy latency`", _when(latency["date_utc"]) if latency else "not run", "-", f"{latency['ac05']['requests']} measured requests" if latency else "-", f"AC05 {latency['ac05']['result']} (this machine)" if latency else "not run"])
    for mode in ("container", "process"):
        record = rec["rehearsal"][mode]
        rows.append([f"Rollback rehearsal, {mode} level", "`python -m med_deploy rehearse`", _when(record["date_utc"]) if record else "not run", "-", f"{len(record['steps'])} steps" if record else "-", _status(record["passed"]) if record else "not run"])
    browser = rec["browser"]
    rows.append(["Review screen container in a browser (manual page text, compared with the API)", "`python -m med_deploy browser-check`", _when(browser["date_utc"]) if browser else "not run", "-", "-", _status(browser["passed"]) if browser else "not run"])
    out.append(_table(["Check", "Command", "Date", "Time", "Result", "Status"], rows) + "\n")
    out.append(
        "The release gate is the full `pytest` and `python -m med_data validate`. The full suite rebuilds the dataset in memory and re-checks long parity runs, "
        "so it takes about nine minutes; CI does not run it. The fast selection deselects the tests marked `slow` (listed under [Test layers](#test-layers)).\n"
    )

    out.append("## Test layers\n")
    out.append(
        _table(
            ["Layer", "Selection", "What it covers"],
            [
                ["Scenario regression", "`tests/test_phase9.py`", "Recorded validation fixtures through the frozen bundle: decision, score, provenance, codes, limitations, and failure behavior"],
                ["Software and contract", "`pytest -m \"not slow\"`", "Phases 2 to 9 unit and contract tests, public-document checks, packaging checks"],
                ["End to end", "`python -m med_deploy smoke`", "The real review screen script against a live API over HTTP, with a disposable feedback file"],
                ["Release gate", "`pytest` and `python -m med_data validate`", "Everything above plus the dataset rebuild and the full-history parity tests"],
            ],
        )
        + "\n"
    )
    out.append("Existing tests marked `slow` (marker registered in `pyproject.toml`; no test was edited or removed apart from that marker):\n")
    out.append(
        _table(
            ["Test", "Why it is slow"],
            [
                ["`tests/test_phase2.py::test_published_contract_passes_validation`", "Runs the full quality checklist on the rebuilt dataset"],
                ["`tests/test_phase2.py::test_roundtrip_and_published_checksums`", "Writes and re-reads the rebuilt dataset"],
                ["`tests/test_phase2.py::test_manifest_timestamp_and_family_must_match_draft`", "Re-runs the quality checklist on an altered manifest"],
                ["`tests/test_phase2.py::test_swapped_manifest_assignment_is_rejected`", "Re-runs the quality checklist on an altered manifest"],
                ["`tests/test_phase2.py::test_scoring_view_hides_labels`", "Builds a scoring view from the full history"],
                ["`tests/test_phase3.py::test_real_history_and_scoring_view_agree`", "Compares batch and single-draft features over real history"],
                ["`tests/test_phase4.py::test_score_query_matches_batch_and_scoring_view`", "Scores sampled drafts through both paths against the stored batch scores"],
            ],
        )
        + "\n"
    )

    out.append("## Scenario regression suite\n")
    scenarios = rec["scenarios"]
    if not scenarios:
        out.append(_missing("scenario_regression.json"))
    else:
        out.append(
            "Fixtures are fictional `validation_product_like` drafts chosen by rule from the policy's stored validation decisions, never by draft id and never from a frozen test subset. "
            "Each fixture records its source, the outcome the product wants (a misdirected email should warn, a legitimate one should allow), and the outcome the frozen bundle produces. "
            "Where they differ the fixture is a **known miss**: it stays in the suite, and the suite asserts what the bundle does today, so an improvement and a regression both fail it and force a reviewed update. "
            "The record holds draft ids, scores, and codes, and no address, subject, or body.\n"
        )
        t_warn = scenarios["bundle"]["T_warn"]
        rows = []
        for item in scenarios["fixtures"]:
            if item["kind"] != "draft":
                continue
            expected = item["expected"]
            recipients = expected["recipients"]
            codes = sorted({c["code"] for r in recipients for c in r["reason_codes"]})
            limits = sorted({c["code"] for r in recipients for c in r["evidence_limitations"]})
            rows.append(
                [
                    f"`{item['key']}`",
                    f"`{item['source']['draft_id']}` ({item['scenario']['id']})",
                    item["desired"],
                    expected["decision"] + (" (known miss)" if item["known_miss"] else ""),
                    _score(expected["email_risk_score"]),
                    f"{expected['email_risk_score'] - t_warn:+.2e}",
                    f"{len(recipients)} / {sum(1 for r in recipients if r['flagged'])}",
                    ", ".join(f"`{c}`" for c in codes + limits) or "none",
                ]
            )
        out.append(_table(["Fixture", "Source draft (scenario)", "Desired", "Recorded outcome", "Email risk score", "Minus `T_warn`", "Recipients / flagged", "Codes and limitations"], rows) + "\n")
        out.append("Selection rules (applied to `artifacts/med-policy-v2/validation_scores.csv`):\n")
        out.append("\n".join(f"- `{item['key']}`: {item['source']['selection']} Guards: {item['guards']}" for item in scenarios["fixtures"] if item["kind"] == "draft") + "\n")
        out.append("Derived fixtures (one transformation of the routine fixture's request each):\n")
        rows = []
        for item in scenarios["fixtures"]:
            if item["kind"] != "derived":
                continue
            expected = item["expected"]
            outcome = f"HTTP {expected['status_code']} {expected['category']}: {expected['message']}" if expected["status"] == "unable_to_assess" else f"{expected['decision']}, {len(expected['recipients'])} recipients, first recipient roles {expected['recipients'][0]['roles']}"
            rows.append([f"`{item['key']}`", item["derivation"], outcome])
        out.append(_table(["Fixture", "Derivation", "Recorded outcome"], rows) + "\n")
        known = [item for item in scenarios["fixtures"] if item.get("known_miss")]
        out.append(
            "**Known misses kept in the suite:** "
            + ", ".join(f"`{item['key']}` ({item['scenario']['id']}, email risk score {_score(item['expected']['email_risk_score'])} against `T_warn` {t_warn!r})" for item in known)
            + ". These are the lookalike replacement, the familiar-recipient topic mistake, and the mistaken first contact. The policy allows them on every validation and test subset (see the [model card](" + STATIC_LINKS["card"] + ")); the suite does not hide them and does not claim them as detections.\n"
        )
        out.append(
            "**What the comparator detects.** `med_deploy.scenarios.compare` flags a changed decision, a score that moved by more than 1e-9 (a decision never gets a tolerance), "
            "changed provenance (model, feature, policy, and snapshot versions, `T_warn`, blocking), a missing or extra reason code or evidence limitation, a changed recipient list or role, "
            "an email risk that is not the maximum recipient risk, a decision that does not follow the cutoff (equality must warn), flagged recipients that are not exactly those at or above the cutoff, "
            "and any failure response that carries a decision, a score, recipients, or the word `allow`. `test_the_comparator_detects_a_changed_decision_score_provenance_or_limitation` and "
            "`test_an_unable_to_assess_that_carries_a_decision_is_detected` apply each change to a real response and require it to be flagged; "
            "`test_a_broken_bundle_fails_every_assessed_fixture` requires a service with a missing bundle to fail every assessed fixture.\n"
        )

    mutations = rec["mutations"]
    if mutations:
        out.append("**Mutation check** (`python -m med_deploy mutation-check`, " + _when(mutations["date_utc"]) + "). " + mutations["method"][0].upper() + mutations["method"][1:] + ". "
                   f"Control: the unmutated copy passes {mutations['control']['fixtures'] - mutations['control']['failed']} of {mutations['control']['fixtures']} fixtures.\n")
        out.append(_table(["Mutation", "File", "What it changes", "Fixtures failed", "First problem reported", "Caught"], [[f"`{item['mutation']}`", f"`{item['file']}`", item["change"], f"{item['failed']} of {item['fixtures']}", item["first_problem"], "yes" if item["detected"] else "NO"] for item in mutations["mutations"]]) + "\n")
    else:
        out.append(_missing("mutation_checks.json"))

    out.append("## Coverage of the required checks\n")
    rows = []
    for topic, tests in COVERAGE.items():
        rows.append([topic, "<br>".join(f"`{node.split('::')[1]}` ({node.split('::')[0].split('/')[1]}; {layer})" for node, layer in tests)])
    out.append(_table(["Topic", "Tests (file; layer)"], rows) + "\n")
    out.append("Existing coverage is cited rather than copied. Phase 9 tests add the scenario regression, the packaging checks, and the smoke. A test requires every cited test to exist and its layer to match its `slow` marker.\n")

    out.append("## Artifact compatibility\n")
    for scope, title in (("api", "API"), ("ui", "Review screen")):
        record = rec["bundle"][scope]
        if not record:
            out.append(_missing(f"bundle_check_{scope}.json"))
            continue
        out.append(f"**{title} bundle check** (`python -m med_deploy check-bundle --scope {scope}`): {_status(record['ok'])}.\n")
        out.append(_table(["Check", "Result", "Detail"], [[f"`{c['name']}`", _status(c["passed"]), c["detail"]] for c in record["checks"]]) + "\n")
        bundle = record["bundle"]
        out.append(
            f"Versions: dataset `{bundle.get('dataset_version')}`, features `{bundle.get('feature_spec_version')}`, model `{bundle.get('model_version')}`, policy `{bundle.get('policy_version')}`; "
            f"`T_warn = {bundle.get('T_warn')!r}`; blocking enabled: {bundle.get('blocking_enabled')}.\n"
        )
    api_record = rec["bundle"]["api"]
    if api_record:
        shown = [item for item in api_record["files"] if item["path"] and (item["path"].endswith(("model.joblib", "policy.json", "artifact_manifest.json", "dataset_manifest.json")))]
        out.append(_table(["File", "Bytes", "SHA-256"], [[f"`{item['path']}`", f"{item['bytes']:,}", f"`{item['sha256']}`"] for item in shown]) + "\n")
    digests = rec["digests"]
    if digests:
        out.append(
            "**Anchored digests.** Nothing else checksums `policy.json` (it holds the model's and the feature manifest's checksums, none of itself) or the two stored validation files the review screen reads, "
            "so a changed cutoff or a rewritten validation table that kept its shape would pass a structural check. Both scopes therefore compare the files they copy with "
            f"`artifacts/med-deploy-v1/bundle_digests.json`, recorded {_when(digests['date_utc'])} after proving that each digest equals the SHA-256 of the blob at commit `{digests['verified_against']['commit'][:12]}` (`{digests['verified_against']['git_ref']}`, before Phase 9). "
            "The image builds run the same check with the manifest bind-mounted, so it is in the build context but not in the image.\n"
        )
        out.append(_table(["File", "Checked by scope", "Bytes", "SHA-256 (anchored)"], [[f"`{path}`", ", ".join(scope for scope, paths in digests["scopes"].items() if path in paths), f"{item['bytes']:,}", f"`{item['sha256']}`"] for path, item in digests["files"].items()]) + "\n")
    else:
        out.append(_missing("bundle_digests.json"))
    out.append(
        "The check runs the same verification the API performs at startup, without loading the history index and without scoring. "
        "`test_published_bundle_passes_the_check_and_a_damaged_copy_fails` shows it failing on a flipped byte, a missing policy, and a policy that names another version. "
        "The previous bundle (`med-policy-v1`) is not loadable by the current code and is not a compatible bundle; see [the runbook](" + STATIC_LINKS["runbook"] + ").\n"
    )

    out.append("## End-to-end smoke\n")
    for mode, title in (("process", "API as a local process (disposable feedback file in a temporary directory)"), ("container", "API and review screen as containers (feedback file on the bind mount)")):
        record = rec["smoke"][mode]
        out.append(f"**{title}**, {_when(record['date_utc']) if record else 'not run'}: {_status(record['passed']) if record else 'not run'}.\n")
        if record:
            out.append(_table(["Step", "Result", "Detail"], [[f"`{c['name']}`", {True: "passed", False: "FAILED", None: "not verified"}[c["passed"]], c["detail"]] for c in record["checks"]]) + "\n")
    out.append(
        "The review screen runs under Streamlit's headless `AppTest`, so every call is a real HTTP request to the service. The check compares what the screen shows with what the API returns for the same request, sent directly. "
        "It needs a screen and an API from the same bundle. For the container the screen script runs on the host against the container's API; the screen container itself is checked through its health endpoint and in a browser (below).\n"
    )
    if browser:
        out.append(
            f"**Review screen container in a browser** ({_when(browser['date_utc'])}, manual): the page for the `{browser['example']}` example was opened at `{browser['page']}`, its visible text saved, and `browser-check` compared it with the API's response for the same draft: "
            f"decision `{browser['shown_in_browser']['decision']}` (API `{browser['from_the_api']['decision']}`), email risk score {browser['shown_in_browser']['email_risk_score']} (API {browser['from_the_api']['email_risk_score']}), "
            f"cutoff {browser['shown_in_browser']['t_warn']} (API {browser['from_the_api']['t_warn']}), {browser['shown_in_browser']['flagged_count']} flagged recipient(s) (API {browser['from_the_api']['flagged_count']}), "
            f"codes {', '.join('`' + c + '`' for c in browser['shown_in_browser']['codes'])}. Result: {_status(browser['passed'])}.\n"
        )

    out.append("## Warm latency\n")
    if not latency:
        out.append(_missing("latency_api_image.json"))
    else:
        out.extend(_latency_section(latency, rec["phase6_latency"]))

    out.append("## Install, pins, and images\n")
    if clean:
        out.append(
            f"**Clean checkout** ({_when(clean['date_utc'])}): a scratch copy of the working tree ({clean['files_copied']} files: tracked files and new files that are not ignored), a fresh virtual environment on Python {clean['venv_python']} "
            f"(tested: {clean['tested_python']}), and every CI step in order: {_status(clean['passed'])}.\n"
        )
        out.append(_table(["Step", "Command", "Exit", "Time"], [[item["step"], f"`{item['command']}`", item["exit_code"], _minutes(item["seconds"])] for item in clean["steps"]]) + "\n")
        env = clean.get("environment_of_the_fresh_venv")
        if env:
            constraints = env["constraints"]
            out.append(
                f"In the fresh environment {env['packages']} third-party packages were installed; {constraints['pinned']} are pinned; installed but not pinned: {len(constraints['installed_but_not_pinned'])}; installed at another version than pinned: {len(constraints['version_differs'])}. "
                f"pyarrow importable: {env['pyarrow_importable']}.\n"
            )
    else:
        out.append(_missing("clean_checkout.json"))
    images = rec["images"]
    if images:
        rows = []
        for name in ("api", "ui"):
            item = images["images"][name]
            env = item["environment"]
            rows.append([f"`med-{name}`", f"`{item['identity']['id']}`", item["identity"]["architecture"], _mib(item["identity"]["size_bytes"]), env["python"], env["packages"], "yes" if env["matches_constraints"] else "NO", "yes" if env["pyarrow_importable"] else "no"])
        out.append(_table(["Image", "Id (content-addressed)", "Architecture", "Size", "Python", "Packages", "Matches `constraints.txt`", "pyarrow importable"], rows) + "\n")
        out.append(f"Both images are built from `{images['images']['api']['base_image']}` (Python {images['images']['api']['environment']['python']}). Installs used wheels only (`pip --only-binary=:all:`).\n")
    else:
        out.append(_missing("images.json"))
    rebuild = rec["rebuild"]
    if rebuild:
        out.append(_rebuild_section(rebuild))

    out.append("## Checks not run, and limits\n")
    limits = [
        "The full `pytest` and `python -m med_data validate` are the release gate and are not part of CI. Their results are in the table above.",
        "GitHub Actions was not executed: `.github/workflows/ci.yml` is checked by a test that it contains the same steps as the clean-checkout run, and its YAML parses, but no GitHub runner ran it.",
        "Measurements are from one machine and one container runtime (Docker Desktop on macOS). Container latency includes the runtime's port forwarding and the VM it runs in.",
        "No Linux host, Windows host, registry push, or hosted deployment was used or tested. The container user (uid 10001) must be able to write the feedback folder; on Linux that is a documented step, not a tested one.",
        "The review screen container is verified through its health endpoint and one manual browser check of a page it served. The screen script itself is exercised headlessly on the host against the container API, not inside the container.",
        "There is no live hot swap, canary, or shadow router. The rollback was rehearsed as a swap of a known-good image for failing candidates, not as a promotion of a different healthy model.",
        "Monitoring is a simulation over fictional validation mail; nothing here is production telemetry.",
        "No check re-evaluated the frozen policy, retrained or refit anything, or scored a frozen test draft. The recorded Phase 5 test result stands as it was.",
    ]
    platform_record = rec["platform"]
    if platform_record:
        limits.append(
            f"A second CPU architecture was checked ({platform_record['architecture']}, {_when(platform_record['date_utc'])}): scenario regression {platform_record['regression']['passed']} passed, {platform_record['regression']['failed']} failed; see the record `other_platform_check.json`."
        )
    else:
        limits.append("Only one CPU architecture (the one this machine runs) was measured.")
    if not rebuild:
        limits.append("The rebuild of features and model into a scratch directory was not run; the procedure is documented in [REPRODUCIBILITY.md](REPRODUCIBILITY.md).")
    out.append("\n".join(f"- {item}" for item in limits) + "\n")
    return "\n".join(out)


def _latency_section(latency: dict, phase6: dict | None) -> list[str]:
    out = []
    ac05 = latency["ac05"]
    target = latency["target"]
    environment = latency["environment_of_measured_process"]
    out.append(
        f"Measured {_when(latency['date_utc'])} against the API container. {latency['claim'][0].upper() + latency['claim'][1:]}. "
        f"This is a new Phase 9 record, stored apart from the one-shot Phase 6 record, which was not touched; it is not a second evaluation of the frozen policy. "
        f"Every request is a fictional `{latency['subset']}` draft.\n"
    )
    out.append(f"- **Timing boundary:** {latency['boundary']}. Server side: {latency['server_boundary']}.")
    workload = latency["workload"]
    out.append(f"- **Workload:** {workload['drawn']}. Warm-up: {workload['warmup_calls']} calls, {workload['warmup']}. AC05 run: {ac05['requests']} measured requests, one in flight (concurrency {ac05['concurrency']}). Wall time {ac05['wall_seconds']} s.")
    out.append("- **Recipient-count mix of the measured requests:** " + ", ".join(f"{count} with {recipients} recipient(s)" for recipients, count in ac05["recipient_mix"].items()) + ".")
    out.append(f"- **Failures:** {ac05['failures']} of {ac05['requests']} (statuses: {_kv(ac05['statuses'])}).")
    parity = ac05["parity_with_stored_validation_scores"]
    out.append(f"- **Parity with the stored validation table:** {parity['decisions_matching']} of {parity['compared']} decisions match; largest email risk score difference {parity['max_abs_email_risk_difference']:.2e}.\n")
    client, server = ac05["client"], ac05["server"]
    out.append(
        _table(
            ["AC05 run", "p50", "p95", "p99", "max"],
            [
                ["Client (HTTP round trip)", _ms(client["p50_ms"]), _ms(client["p95_ms"]), _ms(client["p99_ms"]), _ms(client["max_ms"])],
                ["Server (`duration_ms`)", _ms(server["p50_ms"]), _ms(server["p95_ms"]), _ms(server["p99_ms"]), _ms(server["max_ms"])],
            ],
        )
        + "\n"
    )
    verdict = f"**AC05: {ac05['result']}** on the client p95 of {_ms(ac05['client_p95_ms'])} against the provisional {latency['target_p95_ms']:.0f} ms target, on this machine and this container configuration only ([acceptance criteria]({STATIC_LINKS['ac']}))."
    if phase6:
        verdict += f" For comparison, the Phase 6 one-shot record (in-process test client, no network, {phase6['measured_calls']:,} calls) has a client p95 of {_ms(phase6['client_p95_ms'])}. The two boundaries differ, so the numbers are not interchangeable."
    out.append(verdict + "\n")
    concurrent = latency["concurrent_probe"]
    out.append(
        f"**Small concurrent load** (not AC05): {concurrent['clients']} clients, {concurrent['requests']} requests, {concurrent['wall_seconds']} s, {concurrent['requests_per_second']} requests per second; "
        f"client p50 {_ms(concurrent['client']['p50_ms'])}, p95 {_ms(concurrent['client']['p95_ms'])}, p99 {_ms(concurrent['client']['p99_ms'])}; failures {concurrent['failures']}; "
        f"{concurrent['parity_with_stored_validation_scores']['decisions_matching']} of {concurrent['parity_with_stored_validation_scores']['compared']} decisions match the stored table. "
        f"The client p95 is {'below' if concurrent['client']['p95_ms'] < latency['target_p95_ms'] else 'ABOVE'} the {latency['target_p95_ms']:.0f} ms target. "
        "AC05 specifies one request in flight, so this probe does not decide it; it shows that one API process with two CPUs queues requests when four clients send at once, "
        "and that the margin under the target narrows with concurrency. Capacity planning is out of scope for this demo.\n"
    )
    maximum = latency["maximum_input_probe"]
    out.append(
        f"**Maximum-input probe** (reported separately, as the acceptance criteria ask): {maximum['requests']} requests of {maximum['shape']}; "
        f"statuses {_kv(maximum['statuses'])}{'; failure categories ' + _kv(maximum['failure_categories']) if maximum.get('failure_categories') else ''}; client p50 {_ms(maximum['client']['p50_ms'])}, p95 {_ms(maximum['client']['p95_ms'])}, max {_ms(maximum['client']['max_ms'])}; server p95 {_ms(maximum['server']['p95_ms'])}. "
        "These drafts are built from validation drafts with randomly chosen visible recipients; their decisions are not a detection claim.\n"
    )
    out.append("**What was measured:**\n")
    image = target.get("image", {})
    container = target.get("container", {})
    docker = target.get("docker", {})
    rows = [
        ["Served bundle", f"`{latency['served']['model_version']}`, `{latency['served']['feature_spec_version']}`, `{latency['served']['policy_version']}`, snapshot `{latency['served']['snapshot_id']}`, contract `{latency['served']['contract_version']}`, `T_warn = {latency['served']['T_warn']!r}`"],
        ["API startup (bundle load)", f"{latency['served']['load_seconds']} s"],
    ]
    if target["kind"] == "container":
        rows += [
            ["Image", f"`{image.get('id')}` ({image.get('architecture')}, {_mib(image.get('size_bytes'))})"],
            ["Container limits", f"{container.get('cpus')} CPUs, memory limit {_mib(container.get('memory_limit_bytes'))}; peak memory after the run {_mib(target.get('peak_memory_bytes_after_run'))}"],
            ["Container settings", f"user {container.get('user')}, read-only root filesystem {container.get('read_only_root_filesystem')}, dropped capabilities {', '.join(container.get('cap_drop') or []) or 'none'}, published ports {_ports(container.get('published_ports') or {})}"],
            ["Container runtime", f"Docker {docker.get('server_version')} (client {docker.get('client_version')}), {docker.get('operating_system')}, {docker.get('architecture')}, VM with {docker.get('cpus')} CPUs and {_mib(docker.get('memory_bytes'))}"],
        ]
    rows += [
        ["Interpreter in the measured process", f"Python {environment['python']} on {environment['platform']}"],
        ["pyarrow importable in the measured process", "yes" if environment["pyarrow_importable"] else "no"],
        ["pandas string storage in the measured process", _storage(environment["pandas_string_storage"])],
        ["Key packages", ", ".join(f"{name} {version}" for name, version in environment["key_packages"].items())],
        ["Client (this host)", f"{latency['client']['platform']}, Python {latency['client']['python']}, httpx {latency['client']['httpx']}"],
    ]
    out.append(_table(["Item", "Value"], rows) + "\n")
    return out


def _with_scratch_variable(command: str) -> str:
    """`--output <scratch>/x` becomes `--output "$SCRATCH/x"`; every other word is kept as recorded."""
    words = command.split(" ")
    return " ".join(f'"$SCRATCH/{word[len("<scratch>/"):]}"' if word.startswith("<scratch>/") else word for word in words)


def _rebuild_section(rebuild: dict) -> str:
    # The record stores `<scratch>` placeholders; printed as a shell variable so a copied command
    # never turns into a redirection (`SCRATCH` is a scratch directory, for example from `mktemp -d`).
    shown = [_with_scratch_variable(command) for command in rebuild["commands"]]
    lines = [f"**Rebuild into a scratch directory** ({_when(rebuild['date_utc'])}, `SCRATCH` a scratch directory): `{shown[0]}` then `{shown[1]}`, compared with the published files. Published files were not touched: {rebuild['published_files_unchanged']}.\n"]
    lines.append(_table(["File", "Identical bytes", "Note"], [[f"`{item['file']}`", "yes" if item["identical"] else "no", item["note"]] for item in rebuild["files"]]) + "\n")
    lines.append(rebuild["summary"] + "\n")
    return "\n".join(lines)


# --------------------------------------------------------- ROLLBACK_REHEARSAL


def rollback_report(rec: dict) -> str:
    out = ["# Phase 9 — Rollback rehearsal\n"]
    out.append(
        "Generated by `python -m med_deploy report` from `artifacts/med-deploy-v1/rollback_rehearsal_*.json`. The rehearsal is a **local** exercise: "
        "a known-good deployable and a failing candidate, swapped on one machine. It is not a live hot swap, a canary, or a shadow router; none of those exists. "
        "It follows the rollback steps in [the runbook](" + STATIC_LINKS["runbook"] + ") and does not change them.\n"
    )
    out.append("## How the rehearsal works\n")
    out.append(
        "- **Known-good** is a code-plus-bundle deployable with a content-addressed identity that is never edited: an image id for containers, the SHA-256 of the policy, model, and feature manifest for processes.\n"
        "- **A candidate** is the known-good deployable with one injected fault: a flipped byte in `model.joblib` (the policy records the model's SHA-256), or `policy.json` removed. "
        "For containers a candidate is a thin image layered on the known-good image; for processes it is a disposable copy. No published or frozen file is edited in place.\n"
        "- **Verification** of a healthy deployable: `/health`, `/ready` with the versions and `T_warn` of the policy file, every scenario fixture (including an allow, a warning, and the known misses), "
        "and one reviewed-label click that must add exactly one line (no address) to the rehearsal's own feedback file, change no decision, and change no bundle file. "
        "In the container rehearsal the review screen container must also be healthy and must see `/ready` 200 from inside its own network.\n"
        "- **Verification of a failing candidate:** the process is up, `/ready` is 503 with a reason, `/assess` is `unable_to_assess` with no decision, no score, and no versions, "
        "the scenario suite flags every assessed fixture, the health command a container runs fails, and nothing is written to the feedback file. "
        "The review screen script, run headlessly on the host against the failing API, must disable assessment and say the service is not ready. "
        "In the container rehearsal the review screen container must stay healthy and must see `/ready` 503 from inside its own network; a container that is unreachable or unhealthy at any step fails that step.\n"
        "- **Restore:** the known-good deployable is started again and everything above is re-verified.\n"
    )
    for mode, title in (("container", "Container rehearsal"), ("process", "Process-level rehearsal")):
        record = rec["rehearsal"][mode]
        out.append(f"## {title}\n")
        if not record:
            out.append(_missing(f"rollback_rehearsal_{mode}.json"))
            continue
        out.append(f"Run {_when(record['date_utc'])} on `{record['machine']['platform']}`: **{_status(record['passed'])}**. Trigger: {record['trigger']}.\n")
        known = record["identities"]["known_good"]
        if mode == "container":
            docker = record["docker"]
            out.append(f"Runtime: Docker {docker['server_version']}, {docker['operating_system']} ({docker['architecture']}), {docker['cpus']} CPUs, {_mib(docker['memory_bytes'])}.\n")
            rows = [["known-good", f"`{known['reference']}`", f"`{known['id']}`", "the image the demo runs"]]
            for name, item in record["identities"]["candidates"].items():
                rows.append([f"candidate `{name}`", f"`{item['tag']}`", f"`{item['id']}`", item["construction"]])
            out.append(_table(["Deployable", "Reference", "Image id", "Construction"], rows) + "\n")
            after = record["identities"]["known_good_after"]
            out.append(f"After the last restore the known-good reference names `{after['id']}`; unchanged: {record['identities']['known_good_unchanged']}.\n")
        else:
            files = known["files"]
            out.append(_table(["Known-good bundle file", "SHA-256"], [[f"`{name}`", f"`{digest}`"] for name, digest in files.items()]) + "\n")
            out.append("Candidates: " + "; ".join(f"`{name}`: {item['construction']}" for name, item in record["identities"]["candidates"].items()) + f". Known-good files unchanged afterwards: {record['identities']['known_good_unchanged']}.\n")
        out.append(_table(["Step", "Result", "Seconds"], [[item["step"], _status(item["passed"]) if item["passed"] else "FAILED: " + item["error"], item["seconds"]] for item in record["steps"]]) + "\n")
        out.append("### Observed: healthy deployables\n")
        healthy = [item for item in record["steps"] if item.get("deployable") == "known_good"]
        rows = []
        for item in healthy:
            rows.append(
                [
                    item["step"],
                    f"`{item['image_id']}`" if "image_id" in item else "-",
                    item["seconds_until_the_port_answered"],
                    f"`/ready` {item['ready_http']}; model `{item['served']['model_version']}`, features `{item['served']['feature_spec_version']}`, policy `{item['served']['policy_version']}`, `T_warn = {item['served']['T_warn']!r}`, blocking {'enabled' if item['served']['blocking_enabled'] else 'disabled'}",
                    f"{item['scenario_fixtures']['passed']} passed, {item['scenario_fixtures']['failed']} failed; allow fixture: {item['allow']['decision']}; warning fixture: {item['warning']['decision']}",
                    f"{item['feedback']['lines_added_by_one_click']} line per click; next assessment identical: {item['feedback']['next_assessment_identical']}; bundle files unchanged: {item['feedback']['bundle_files_unchanged']}",
                    f"healthy; sees `/ready` {item['ui_container_sees_ready_http']}" if "ui_container_sees_ready_http" in item else "not started yet" if mode == "container" else "no screen container",
                ]
            )
        out.append(_table(["Step", "Image id", "Seconds until the port answered", "Readiness and versions", "Scenario suite", "Feedback isolation", "Screen container"], rows) + "\n")
        out.append("### Observed: failing candidates\n")
        failing = [item for item in record["steps"] if item.get("deployable") not in (None, "known_good")]
        rows = []
        for item in failing:
            probe = item["assess"]["routine_allow"]
            screen = item["review_screen"]
            rows.append(
                [
                    f"`{item['deployable']}`",
                    item["fault"],
                    f"`/health` {item['health_http']}; `/ready` {item['ready_http']}: {item['ready_reason']}",
                    f"HTTP {probe['http']} `{probe['status']}` (`{probe['category']}`): {probe['message']}; decision {probe['decision']}, score {probe['email_risk_score']}, no versions reported",
                    f"{item['scenario_suite']['flagged_by_the_suite']} of {item['scenario_suite']['assessed_fixtures']} assessed fixtures flagged",
                    f"exit code {item['health_command_exit_code']}",
                    f"{screen['checked_by']}: assessment disabled: {screen['assessment_disabled']}; banner: {screen['banner'][0] if screen['banner'] else 'none'}; decision shown: {not screen['no_decision_shown']}",
                    f"health `{item['ui_process_health']}`; sees `/ready` {item['ui_container_sees_ready_http']}" if "ui_container_sees_ready_http" in item else "no screen container",
                ]
            )
        out.append(_table(["Candidate", "Injected fault", "Health and readiness", "`POST /assess`", "Scenario suite", "Container health command", "Review screen (observed by the screen script on the host)", "Screen container"], rows) + "\n")
        if mode == "container":
            out.append(
                "The review screen container was started once and stayed healthy (health endpoint `ok`) at every step, through both failed candidates and both restorations. "
                "From inside its own network it saw `/ready` 503 for each failing candidate and 200 after each restore. "
                "What the screen *shows* in the failed state was observed with the screen script on the host, not in the container: the container's served page was not opened in a browser in that state (a browser check covers one healthy page, see [the test report](TEST_REPORT.md)).\n"
            )
        out.append(
            f"Published bundle files on disk (policy, model, manifests) are byte-identical before and after: {record['published_bundle_files_unchanged']}. "
            f"The rehearsal's feedback file holds {record['feedback_lines_in_the_rehearsal_file']} lines: one per verified healthy deployable, none from a failing candidate.\n"
        )
        out.append("### Limits of this rehearsal\n")
        out.append("\n".join(f"- {line}" for line in record["limits"]) + "\n")
    out.append("## Commands\n")
    out.append(
        "The published records under `artifacts/med-deploy-v1/` are the outputs of the run described above and are write-once: a command that names one of them is refused. "
        "To rehearse again, write to a scratch directory. The block below makes one with `mktemp -d` and runs as printed from the repository root:\n"
    )
    out.append(
        "```bash\n"
        "docker/build.sh                                  # build med-api:phase9 and med-ui:phase9\n"
        "SCRATCH=\"$(mktemp -d)\"\n"
        "python -m med_deploy images --record \"$SCRATCH/images.json\"\n"
        "python -m med_deploy rehearse --mode container --record \"$SCRATCH/rehearsal_container.json\"\n"
        "python -m med_deploy rehearse --mode process   --record \"$SCRATCH/rehearsal_process.json\"\n"
        "```\n"
    )
    out.append(
        "To roll back the running demo by hand, point compose at the known-good image id, read from the images record, and recreate only the API:\n\n"
        "```bash\n"
        "KNOWN_GOOD=\"$(python -c 'import json; print(json.load(open(\"artifacts/med-deploy-v1/images.json\"))[\"images\"][\"api\"][\"identity\"][\"id\"])')\"\n"
        "MED_API_IMAGE=\"$KNOWN_GOOD\" docker compose up -d --no-build --force-recreate --no-deps api\n"
        "```\n\n"
        "Then check `GET /ready`, run `python -m med_deploy regress --api http://127.0.0.1:8000`, and confirm the container's image id with `docker inspect`. "
        "Do not edit a bundle inside a running container; a new bundle is a new image.\n"
    )
    out.append(
        "## What this does not cover\n\n"
        "- A live switch between two loadable bundles, a shadow mode that records a decision without showing it, and a per-sender routing switch are **future capabilities**; none was built.\n"
        "- The previous bundle (`med-policy-v1`) is refused by the current code by design, so it cannot be a rollback target; a rollback needs the previous code and its bundle as a pair, which is what a known-good image is.\n"
        "- A candidate here is the known-good bundle with a fault. The rehearsal shows that a broken bundle fails closed and that the known-good deployable restores and verifies; it does not show that a different, healthy model can be promoted. Promotion still needs the gates in [the runbook](" + STATIC_LINKS["runbook"] + ").\n"
    )
    return "\n".join(out)


# ---------------------------------------------------------- REPRODUCIBILITY


def reproducibility_report(rec: dict) -> str:
    out = ["# Phase 9 — Reproducibility\n"]
    out.append(
        "How to install the tested environment, verify the published bundle, run the project, and, separately, how the bundle was produced. "
        "Measured results in this page come from `artifacts/med-deploy-v1/` and are generated by `python -m med_deploy report`.\n"
    )
    out.append("## Runtime and pins\n")
    out.append(
        f"- **Python {V.TESTED_PYTHON}** is the tested interpreter (`.python-version`; the images and CI use it). `pyproject.toml` still says `requires-python = \">=3.11\"`, so the core install stays light and works on other 3.11 and later interpreters; only {V.TESTED_PYTHON} is the tested one.\n"
        "- **`constraints.txt`** pins every third-party package of the core install and of the `dev`, `ui`, and `monitor` extras, exactly as tested. It pins third-party packages only, never this project: a raw `pip freeze` would add an editable install of the project pinned to one commit and is not portable. "
        "A constraints file installs nothing by itself: `pip install -c constraints.txt .` takes only what the core needs, so the API image does not get Streamlit or pyarrow even though both are pinned.\n"
        "- **Build backend.** The project builds with setuptools from `pyproject.toml`; the build tool is fetched at install time and is not pinned, which affects how this project's own wheel is built, not which third-party versions run.\n"
        "- **Platform-conditional packages.** A freeze made on one platform lacks what another installs: Streamlit needs `watchdog` on Linux but not on macOS. The first Linux image build installed `watchdog` unpinned, which the image check reported, and it is now pinned; a test evaluates the dependency markers of the installed packages for macOS and Linux so a missing pin is caught.\n"
        "- **No new locking tool** was added. To regenerate the pins after a deliberate upgrade, run the tests in an environment built from the new versions and compare `python -m med_deploy environment --freeze` from each platform you support (the Linux images report `environment --constraints constraints.txt` the same way).\n"
    )
    out.append("## Fresh checkout\n")
    out.append(
        "```bash\n"
        f"python{V.TESTED_PYTHON.rsplit('.', 1)[0]} -m venv .venv            # use Python {V.TESTED_PYTHON} to match the tested environment\n"
        "source .venv/bin/activate\n"
        'pip install -c constraints.txt -e ".[dev,ui,monitor]"\n'
        "pip check\n"
        "python -m med_deploy environment --constraints constraints.txt --check   # exits 1 on any difference from the pins\n"
        "python -m med_deploy check-bundle --scope api                            # artifact versions and checksums, no scoring\n"
        "python -m med_deploy check-bundle --scope ui\n"
        "python -m pytest -m \"not slow\" -q                                        # the CI selection\n"
        "python -m med_deploy smoke --spawn                                       # API process plus the review screen, end to end\n"
        "```\n"
    )
    out.append(
        "Release gate (about nine minutes, not run in CI): `python -m pytest` and `python -m med_data validate --data data/med-synth-v4`.\n\n"
        "Start the services without containers, in two virtual environments if you want the API to keep its faster Python string storage (see below):\n\n"
        "```bash\n"
        "python -m med_api serve                # http://127.0.0.1:8000, bundle verified at startup\n"
        "python -m med_ui                       # http://127.0.0.1:8501 (loopback by default; --host to change)\n"
        "```\n"
    )
    out.append("## Measured: fresh-environment installs\n")
    clean = rec["clean"]
    images = rec["images"]
    rows = []
    if clean and clean.get("environment_of_the_fresh_venv"):
        env = clean["environment_of_the_fresh_venv"]
        rows.append(["Fresh virtual environment (extras `dev`, `ui`, `monitor`)", env["platform"], env["python"], env["packages"], "yes" if env["matches_constraints"] else "NO", "yes" if env["pyarrow_importable"] else "no", _storage(env["pandas_string_storage"])])
    if images:
        for name, label in (("api", "API image (core install)"), ("ui", "Review screen image (`ui` extra)")):
            env = images["images"][name]["environment"]
            rows.append([label, env["platform"], env["python"], env["packages"], "yes" if env["matches_constraints"] else "NO", "yes" if env["pyarrow_importable"] else "no", _storage(env["pandas_string_storage"])])
    if rows:
        out.append(_table(["Environment", "Platform", "Python", "Third-party packages", "Every package equals its pin", "pyarrow importable", "pandas string storage"], rows) + "\n")
        out.append("Every installed package equals its pin and none is unpinned (`environment --constraints constraints.txt --check`). `pip check` reported no broken requirements in the fresh virtual environment (a step of the clean checkout).\n")
    else:
        out.append(_missing("clean_checkout.json and images.json"))
    if clean:
        out.append(_table(["Clean-checkout step", "Exit code", "Time"], [[f"`{item['command']}`", item["exit_code"], _minutes(item["seconds"])] for item in clean["steps"]]) + "\n")
    platform_record = rec["platform"]
    if platform_record:
        out.append(
            f"**A second CPU architecture** ({platform_record['architecture']}, {_when(platform_record['date_utc'])}): the same API image recipe was built for `{platform_record['platform']}` and the scenario regression replayed against it: "
            f"{platform_record['regression']['passed']} passed, {platform_record['regression']['failed']} failed. {platform_record['note']}\n"
        )
    out.append("## Why the API is kept apart from pyarrow\n")
    out.append(
        "Streamlit requires pyarrow. When pyarrow is importable, pandas 3 stores strings in Arrow by default. Every result is unchanged, but the data and feature pipeline runs about three times slower "
        "(`python -m med_data validate` took 159.8 s with pyarrow against 49.1 s without, in Phase 7). **Decision: split environments, do not pin pandas in the packages.** "
        "The scoring API image installs the core package only, so pyarrow is not importable in it; the review screen, which never scores, has its own image with pyarrow. "
        "`tests/conftest.py` pins pandas to Python string storage for the test suite. The measured images above record whether pyarrow is importable in each. "
        "`python -m med_deploy environment` reports it for any environment, and the latency record states it for the measured process.\n"
    )
    out.append("## The published bundle, and how it was produced\n")
    out.append(
        "**Using the published frozen bundle** (what a person running the demo does): the dataset `med-synth-v4`, features `med-features-v2`, model `med-model-v2`, and policy `med-policy-v2` are in the repository with checksums. "
        "Nothing is regenerated, refit, or re-evaluated to install or serve them. `check-bundle` verifies them; the API verifies them again at startup and refuses to serve a mismatch.\n"
    )
    out.append(
        "**Rebuilding** is a separate procedure, not part of installing, an image build, or CI. The frozen test subsets of `med-synth-v4` were evaluated once for `med-policy-v2`; a new policy needs a new version and a new frozen dataset version. "
        "The data build refuses to write into a directory that already holds a dataset. The feature and model commands do **not** refuse to overwrite their default output directories, and `med_models run` also rewrites `docs/phase_4` and trains on the published features by default, "
        "so **never run `python -m med_features build` or `python -m med_models run` with default paths**. A rebuild demonstration sends every output to a scratch directory and trains on the scratch features:\n\n"
        "```bash\n"
        "SCRATCH=\"$(mktemp -d)\"\n"
        "python -m med_data build --output \"$SCRATCH/data\"        # into a new directory; compare dataset_manifest.json with the published one\n"
        "python -m med_features build --output \"$SCRATCH/features\"\n"
        "python -m med_models run --features \"$SCRATCH/features\" --output \"$SCRATCH/model\" --docs \"$SCRATCH/docs\"\n"
        "```\n\n"
        "The threshold step (`python -m med_policy select`) and the frozen evaluation (`python -m med_policy evaluate-test`) are one-shot commands and are not part of any rebuild demonstration. "
        "`python -m med_api latency` is the one-shot Phase 6 measurement; Phase 9 measures latency with `python -m med_deploy latency`, which writes a new record.\n"
    )
    rebuild = rec["rebuild"]
    if rebuild:
        out.append("### Rebuild demonstration\n")
        out.append(_rebuild_section(rebuild))
    else:
        out.append("The rebuild above was documented and **not run** in Phase 9.\n")
    out.append(
        "## Files of record\n\n"
        "`constraints.txt`, `.python-version`, `docker/`, `compose.yaml`, `.github/workflows/ci.yml`, `src/med_deploy/`, `tests/test_phase9.py`, and `artifacts/med-deploy-v1/` (write-once measurement records). "
        "Standing rules for the frozen data are in [the data quality and leakage checklist](" + STATIC_LINKS["leakage"] + ").\n"
    )
    return "\n".join(out)


# ------------------------------------------------------------ LOCAL_DEPLOYMENT


def deployment_report(rec: dict) -> str:
    out = ["# Phase 9 — Local deployment\n"]
    out.append(
        "Run the scoring API and the review screen on one machine, as two containers or as plain processes. Everything is a local simulation on fictional data: "
        "both ports are published on `127.0.0.1` only, and nothing here is meant for a public host, real mail, or enterprise authentication. "
        "Decisions are simulated, scores are risk scores, blocking is disabled, and a failure is `unable_to_assess`, never an allow.\n"
    )
    out.append("## Containers\n")
    out.append(
        "Needs Docker with Compose v2 and a running daemon, and a Python environment with the project installed (for `med_deploy`; see [REPRODUCIBILITY.md](REPRODUCIBILITY.md)).\n\n"
        "```bash\n"
        "mkdir -p var/demo                   # the feedback folder (gitignored)\n"
        "docker/build.sh                     # check the bundle, then build med-api:phase9 and med-ui:phase9\n"
        "docker compose up -d --wait         # starts the API, then the screen once the API's /ready succeeds\n"
        "open http://127.0.0.1:8501          # the review screen (API: http://127.0.0.1:8000)\n"
        "python -m med_deploy smoke --api http://127.0.0.1:8000 --ui http://127.0.0.1:8501 --feedback-file var/demo/feedback.jsonl --target container\n"
        "python -m med_deploy regress --api http://127.0.0.1:8000      # the scenario fixtures against the running API\n"
        "docker compose down                 # stop and remove the containers; var/demo is kept\n"
        "```\n"
    )
    out.append(
        "- **Readiness.** `GET /health` says the process is up. `GET /ready` says the bundle loaded and returns the versions and `T_warn`. Do not route requests on `/health` alone. "
        "The API image's Docker health check calls `/ready`, and the screen container starts only after the API reports healthy. The API takes several seconds to start: it verifies every published file before it accepts a request.\n"
        "- **Bundle checks at build time.** Each image build runs `python -m med_deploy check-bundle --image` on what it copied and fails on a missing, extra, or altered file, including `policy.json` and the stored validation files, which are compared with anchored digests, and on a frozen-outcome file. "
        "Image builds never fit, retrain, evaluate, or download data.\n"
        "- **A bad or missing bundle fails closed.** `/ready` returns 503 with a reason and `/assess` returns `unable_to_assess` with no decision and no score. See [the error behavior](" + STATIC_LINKS["errors"] + ") and [ROLLBACK_REHEARSAL.md](ROLLBACK_REHEARSAL.md).\n"
    )
    out.append("## Images\n")
    images = rec["images"]
    reads = rec["reads"]
    if images:
        rows = []
        for name, label in (("api", "API"), ("ui", "Review screen")):
            item = images["images"][name]
            probes = item["write_probes"]
            rows.append(
                [
                    label,
                    f"`{item['dockerfile']}`",
                    f"`{item['identity']['id']}`",
                    _mib(item["identity"]["size_bytes"]),
                    item["identity"]["user"],
                    "yes" if item["environment"]["pyarrow_importable"] else "no",
                    f"{probes['as_the_container_user']['outcome']}; as root on a read-only filesystem: {probes['root_on_a_read_only_filesystem']['outcome']}",
                ]
            )
        out.append(_table(["Image", "Dockerfile", "Id (content-addressed)", "Size", "Runs as", "pyarrow importable", "Write to a bundle file from inside"], rows) + "\n")
        out.append(f"Both are built from `{images['images']['api']['base_image']}`, pinned by tag and by digest of the multi-architecture index. Containers run with a read-only root filesystem, all capabilities dropped, and `no-new-privileges`; limits are in `compose.yaml` (API 2 CPUs and 2 GiB, screen 1 CPU and 1 GiB).\n")
    else:
        out.append(_missing("images.json"))
    out.append("- **Separate images.** The API image has the core install and the model; the screen image has the `ui` extra and **no model, no feature artifact, and no frozen-outcome file**, so it cannot score even by mistake. Every decision the screen shows is the API's, over HTTP.\n")
    out.append("## What each process reads\n")
    if reads and images:
        out.append(
            "Measured, not guessed: each process ran under a Python audit hook that logs every file it opens, was driven with real requests, and the files it opened under `data/` and `artifacts/` are listed. "
            "The per-image ignore lists (`docker/Dockerfile.*.dockerignore`) are default-deny lists of exactly these files, and the build fails if an image holds anything else. "
            "The commands that regenerate documents from stored results (`python -m med_ui walkthrough`, `python -m med_policy report`, `python -m med_api report`) read the recorded Phase 5 test result, `test_evaluation.json`; the walkthrough and `python -m med_api report` remove the file's per-draft members from the text before parsing it, while `python -m med_policy report` parses the whole file because the Phase 5 error-analysis page lists those per-draft outcomes. No served process reads it, and no image contains it.\n"
        )
        for name, label in (("api", "API"), ("ui", "Review screen")):
            process = reads["processes"][name]
            sizes = images["images"][name]["files_in_app"]
            rows = [[f"`{path}`", f"{sizes[path]:,}"] for path in process["read"] if path in sizes]
            out.append(f"**{label}: {len(process['read'])} files read** (matches the bundle check: {process['matches_expected']}; files in the image's `/app`: {len(sizes)}; written anywhere under the repository root: {', '.join(process['written_under_root']) or 'nothing'}).\n")
            out.append(_table(["File", "Bytes"], rows) + "\n")
        out.append(f"Workload while measuring: API: {reads['workload']['api']}. Screen: {reads['workload']['ui']}.\n")
    else:
        out.append(_missing("reads.json and images.json"))
    out.append(
        "Excluded from the images: `.git`, `.venv`, local private notes, `var/` and any local feedback, secrets, tests and docs, the superseded `med-synth-v2` data and the `*-v1` artifacts, `validation_scores.csv` and the evaluation files (for the API), and every file that stores frozen test outcomes.\n"
    )
    out.append("## Feedback: volume, retention, cleanup\n")
    out.append(
        "- The API writes reviewed-label clicks to `/feedback/feedback.jsonl` inside the container: one JSON line per click (request id, contact id, label, versions, time), never an address, subject, or body. "
        "It is the **only writable path**. Compose mounts the host folder `var/demo` (gitignored) there; set `MED_FEEDBACK_DIR` to use another folder.\n"
        "- **Nothing reads the file back into scoring.** A click is not a label until a reviewer accepts it, and it never changes the model, the policy, or the cutoff ([API contract](" + STATIC_LINKS["api"] + ")).\n"
        "- **Retention rule for the demo:** keep the file only while a review session needs it. Delete the folder (`rm -rf var/demo`) when the session ends, and in any case within 30 days. It is fictional data, and a new container starts with whatever the folder holds. "
        "The frozen bundle is baked into the image and owned by root; removing or replacing it means a new image.\n"
        "- On Linux the container user (uid 10001) must be able to write the folder: `chmod a+w var/demo` or `chown 10001 var/demo`. Docker Desktop on macOS needs nothing.\n"
    )
    out.append("## Without containers\n")
    out.append(
        "```bash\n"
        'pip install -c constraints.txt -e ".[dev,ui,monitor]"     # see REPRODUCIBILITY.md\n'
        "python -m med_api serve                                    # API on http://127.0.0.1:8000\n"
        "python -m med_ui                                           # screen on http://127.0.0.1:8501, loopback only by default\n"
        "python -m med_deploy smoke --spawn                         # or: start the API yourself and use --api URL\n"
        "```\n\n"
        "`python -m med_ui` previously listened on every network interface by default; it now listens on `127.0.0.1` and takes `--host` to change that. "
        "Every bundle path can be overridden with `MED_API_POLICY`, `MED_API_MODEL`, `MED_API_FEATURES`, `MED_API_DATA`, and `MED_API_FEEDBACK` (the screen reads `MED_UI_API_URL`, `MED_UI_ROOT`, `MED_UI_DATA`, and `MED_UI_POLICY_DIR`). "
        "To keep the scoring process fast, run the API in an environment without the `ui` extra (pyarrow makes pandas 3 slower, with identical results).\n"
    )
    out.append("## Troubleshooting\n")
    out.append(
        _table(
            ["Symptom", "Likely cause", "What to do"],
            [
                ["`docker compose up --wait` never finishes", "The API is not ready: it found a missing or altered bundle file", "`docker compose logs api` and `curl http://127.0.0.1:8000/ready`; the reason names the file. Rebuild the image from the published files; do not edit a file in place."],
                ["`/ready` is 503 and `/assess` returns `unable_to_assess`", "The service is up with no loaded bundle (by design it fails closed)", "Fix the cause named in `reason`, or restore the known-good image ([ROLLBACK_REHEARSAL.md](ROLLBACK_REHEARSAL.md))."],
                ["The screen shows \"Scoring service is not ready\" and Assess is disabled", "The API is unreachable, not ready, or serves a different bundle than the screen's policy file", "Check `/ready` against `artifacts/med-policy-v2/policy.json` (versions and `T_warn`)."],
                ["A typed address gives `unavailable`", "A well-formed address that is not in the snapshot directory (for example a typo)", "This is the contract, not an outage: pick a contact from the directory."],
                ["Feedback click fails or writes nothing", "The feedback folder is not writable by uid 10001 (Linux), or the request id is not from this API process", "`chmod a+w var/demo`; assess again, then click."],
                ["Port 8000 or 8501 is in use", "Another process holds the port", "Set `MED_API_PORT` or `MED_UI_PORT` before `docker compose up`."],
                ["The API is slow to start", "It verifies every published file (checksums and record counts) and builds the history index", "Wait for `/ready`; the measured start time is in the latency record."],
                ["Slow scoring in a plain process", "pyarrow is importable (the `ui` extra is installed in the API's environment)", "Use a separate environment for the API, or the API image."],
            ],
        )
        + "\n"
    )
    out.append(
        "## Limits\n\n"
        "- Local only. No registry push, hosted deployment, authentication, TLS, or public exposure was built or tested.\n"
        "- Images are built and tested for the architecture of the machine that built them; a second architecture check, if any, is in [TEST_REPORT.md](TEST_REPORT.md).\n"
        "- Monitoring ([the runbook](" + STATIC_LINKS["runbook"] + ")) is a simulation; the containers do not ship telemetry. The API's structured-log allow-list is unchanged.\n"
    )
    return "\n".join(out)


# ------------------------------------------------------------------- writing


def documents(root: Path) -> dict[str, str]:
    rec = load_records(root)
    return {
        "TEST_REPORT.md": test_report(rec),
        "REPRODUCIBILITY.md": reproducibility_report(rec),
        "LOCAL_DEPLOYMENT.md": deployment_report(rec),
        "ROLLBACK_REHEARSAL.md": rollback_report(rec),
    }


def write_documents(root: Path, out_dir: Path = V.DOCS_DIR) -> list[Path]:
    root = Path(root)
    target = root / out_dir
    target.mkdir(parents=True, exist_ok=True)
    written = []
    for name, text in documents(root).items():
        path = target / name
        path.write_text(text.rstrip("\n") + "\n", encoding="utf-8")
        written.append(path)
    return written
